### ISSUE TITLE
Short order on Bitfinex still open...

### ISSUE THREAD

**Issue by mcmunder** [butor/blackbird#137]
... again, thanks for open-sourcing blackbird! Been testing it for a week with docker cloud + microsoft azure and really like it!

However, I just ran into the following issue:

<img width="558" alt="screenshot 2017-03-24 20 44 27" src="https://cloud.githubusercontent.com/assets/5681686/24311272/b66b2f64-10d3-11e7-845f-8363b0e44bf8.png">

The program seems to be stuck there forever... The open position does indeed exist on Bitfinex and it seems to be the result of a limit sell order:

<img width="917" alt="screenshot 2017-03-24 20 53 31" src="https://cloud.githubusercontent.com/assets/5681686/24311557/01db6e72-10d5-11e7-9c71-f38d548dcd43.png">

I can manually close the open position on Bitfinex with a marked sell order but that's not the idea of running a bot I guess ;-)

Any idea what's the problem?

**Comment by boblin** [comment]
The same problem for me:
```
[ 03/24/2017 22:12:36 ]
   Bitfinex: 	960,01 / 961,00
   OKCoin: 	958,76 / 959,18
   Bitstamp: 	947,16 / 950,01
   Kraken: 	947,98 / 953,33
   ----------------------------
   OKCoin/Bitfinex:	 0.09% [target  0.80%, min -0.64%, max  0.29%]
   Bitstamp/Bitfinex:	 1.05% [target  0.80%, min -0.35%, max  1.22%]   trailing  1.14%  1/1
<Bitstamp> Looking for a limit price to fill 0,02 BTC...
<Bitstamp> order book: 4,52@$950,01
<Bitfinex> Looking for a limit price to fill 0,02 BTC...
<Bitfinex> order book: 3,94@$960,03

[ ENTRY FOUND ]
   Date & Time:       03/24/2017 22:12:36
   Exchange Long:     Bitstamp (id 2)
   Exchange Short:    Bitfinex (id 0)
   Fees:              0,25% / 0,20%
   Price Long:        $950,01 (target)
   Price Short:       $960,03 (target)
   Spread:            1,05%
   Cash used:         $15,00 on each exchange
   Exit Target:       -0,35%

<Bitstamp> Trying to send a "buy" limit order: 0,02@$950,01...
<Bitstamp> Done (order ID: 202�925�985)

<Bitfinex> Trying to send a "sell" limit order: 0,02@$960,03...
<Bitfinex> Done (order ID: -2�141�136�781)

Waiting for the two orders to be filled...
Short order on Bitfinex still open...
Short order on Bitfinex still open...
Short order on Bitfinex still open...
Short order on Bitfinex still open...
Short order on Bitfinex still open...
```

**Comment by greatwolf** [comment]
I'm wondering, how big is the `order_id`(eg. how many digits is it)?

**Comment by bejito** [comment]
Yep, looks like bitfinex orderIds are too big now.
Fixed it locally, here is the code: https://github.com/butor/blackbird/pull/138

**Comment by boblin** [comment]
Hi @greatwolf,

I just compiled current version with PR #138, but it still hangs:
```
<Kraken> Trying to send a "buy" limit order: 0,02 @ $942,64...
<Kraken> Done (transaction ID: OWHFJG-SQGUX-YT5QUN)

<Bitfinex> Trying to send a "sell" limit order: 0,02@$954,31...
<Bitfinex> Done (order ID: -2�132�946�650)

Waiting for the two orders to be filled...
<Kraken> No order exists
Short order on Bitfinex still open...
Short order on Bitfinex still open...
Short order on Bitfinex still open...
```

There is probably problem to get info about position, because order on Bitfinex exists:

![snimek obrazovky porizeny 2017-03-25 23-20-03](https://cloud.githubusercontent.com/assets/15293/24326586/a655b50c-11b1-11e7-89fb-b20e8780aa78.png)

**Comment by muffininvoices** [comment]
I'm having the same issue - Bitfinex/Bitstamp. Compiled on (095b3f0) a few hours ago on a new machine.


```
<Bitstamp> Done (order ID: 203,273,352)

<Bitfinex> Done (order ID: -2,133,372,473)
```

Randomized the last 6 digits of both order IDs.

**Comment by greatwolf** [comment]
I've pushed a changeset that treats the `orderId` as a string under the new branch `Fix_issue_137`. It'll need some testing though. See if that corrects the open order issue.

**Comment by muffininvoices** [comment]
@greatwolf appreciated

It appears to have solved the issue for me. The Bitfinex orders are now correctly identified as filled.

**Comment by jackeown** [comment]
I can confirm as well.  I was having this same issue, but this changeset fixed it.  Thanks!

**Comment by greatwolf** [comment]
That's good to hear, I'll go ahead and merge the branch into master.

**Comment by cihanbilir** [comment]
Hi,

By bitfinex order still won't complete.
I'm suspicious of the negative sign on the order id but not sure:

> <Bitfinex/> Trying to send a "sell" limit order: 0.03@$1040.00...
> <Bitfinex/> Done (order ID: -2093402821)
> .
> .
> .
> 
after two days since the spread closed:

> Short order on Bitfinex still open...
> Short order on Bitfinex still open...

**Comment by greatwolf** [comment]
Can you check if the submitted order shows up on the finex web interface? If it's on the list, you can actually inspect the html source for the order id. eg.

    <tr id="order_2108174286">

This will confirm whether their order id can have a negative symbol or not.

**Comment by cihanbilir** [comment]
I closed that order manually this morning, it's listed in the order history but the order id in the row tag is interestingly totally different. I searched for it and the related order id is nowhere in the html source. I'll check it again in the live orders section if this happens again, thank you.

And how do you configure _not_ to use the margin short feature? I'd prefer not to use it too (until it's absolutely fixed) as all my problems in my last 5-6 iterations were due to this. And how efficient would that be? It would reduce your chances to find a spread by half, no?

**Comment by greatwolf** [comment]
Try checking the trade history and order history under 'Reports'. The order id should be the first column.

As far as turning off margin short, I don't think you can since blackbird relies on it when taking a short position on one side.

**Comment by cihanbilir** [comment]
OK, I caught another case of the same situation:

![screen shot 2017-04-06 at 09 02 55](https://cloud.githubusercontent.com/assets/11620711/24740051/df781362-1aa7-11e7-8890-f7b1fe319d8f.png)
16 hours later:
![screen shot 2017-04-06 at 09 04 15](https://cloud.githubusercontent.com/assets/11620711/24740086/0a85842c-1aa8-11e7-8294-8d20a488f9c1.png)
And still running...
---
![screen shot 2017-04-06 at 09 05 59](https://cloud.githubusercontent.com/assets/11620711/24740141/575848c0-1aa8-11e7-903c-89705d592139.png)

The order seen on blackbird logs (first screenshot) is the one on the bitfinex console (last screenshot), I know it because the amounts and the timestamps are identical. But the id's don't match. It's not on the live orders tab it's on the order "history" and it is marked as executed, so blackbird will never be able to close the order.

I never managed to automatically complete an order with blackbird due to this problem.

**Comment by jackeown** [comment]
It worked for me after you switched it to a string in the code.  The int
didn't work (I think because their order numbers finally got larger than
2^32 / 2) So although the api sent the order number, it was being stored as
a 32 bit integer which made it negative instead and bitfinex wouldn't
understand when asking about it.

**Comment by greatwolf** [comment]
Can you check that `json_int_t` is 64 bits in width? According to [Jansson docs](http://jansson.readthedocs.io/en/2.8/apiref.html#c.json_int_t) `json_int_t` falls back to `long` if `long long` isn't supported by the compiler.

eg. The following should compile without failing any of the `static_asserts`:

    #include "jansson.h"
    #include <type_traits>


    int main()
    {
      static_assert(sizeof(json_int_t) == 8, "");
      static_assert(!std::is_same<json_int_t, int>::value, "");
      static_assert(!std::is_same<json_int_t, long>::value, "");
    }

**Comment by cihanbilir** [comment]
I'm so sorry, I'm sure I did (build after pull), but apparently I haven't.

This is fixed for me too now.

Thank you very much.

**Comment by mdrankin** [comment]
I'm seeing the same issue today - "Short order on Bitfinex still open..." and I indeed do still have a position open on Bitfinex. Was built with master build yesterday.
